-- USER SQL
CREATE USER "BALL" IDENTIFIED BY "3602"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "BALL" QUOTA 10M ON "USERS";

-- ROLES
GRANT "DBA" TO "BALL" ;
GRANT "CONNECT" TO "BALL" ;
GRANT "RESOURCE" TO "BALL" ;

-- SYSTEM PRIVILEGES

